### ISSUE TITLE
Rewrite scraper() to read tableu dashboards.

### ISSUE THREAD

**Issue by sorenrood** [tutorly/sherlock#19]
SPU changed their tracking website. New page: https://tableau.spu.edu/views/CovidTrackingDashboard/COVIDCases?:embed=y&:showVizHome=no&:host_url=https%3A%2F%2Ftableau.spu.edu%2F&:embed_code_version=3&:tabs=no&:toolbar=no&:showAppBanner=false&:showShareOptions=false&:display_spinner=no&:loadOrderID=0

**Comment by ThouShawNotPass** [comment]
fuck.

Justin Shaw
UW Class of 2023
Co-Founder, Tutorly

**Comment by sorenrood** [comment]
I embedded the dashboard on https://sorenrood.com/covid.html

They just removed it from their website- probably updating it.

**Comment by ThouShawNotPass** [comment]
That’s dope dude!

**Comment by sorenrood** [comment]
We decided not to pursue this. Closing.
